### ISSUE TITLE
PHP7 Compatibility

### ISSUE THREAD

**Issue by stixpunk** [phpgearbox/pdf#4]
Tested and working but Gears\String must be replaced to some other name -> "String" is reserved name in php7

**Comment by brad-jones** [comment]
Checkout the latest dev-master version of https://github.com/phpgearbox/string, it has been completely re-written using more modern PHP. The plan is to update all my phpgearbox packages to be PHP7 compat. Obviously that's a while off yet... feel free to send through a PR with the old Gears\String swapped out with the new version not sure how much work is involved though...

**Comment by stixpunk** [comment]
sorry, my mistake. i install pdf with composer "gears/pdf": "*" and get older version of string

**Comment by brad-jones** [comment]
The new versions of Gears\String probably won't work with this package, if it does great but I think you will run into issues if using dev-master or one of the v1-RC releases.
