### ISSUE TITLE
Unable to save or generate PDF file

### ISSUE THREAD

**Issue by mjaseo** [phpgearbox/pdf#8]
Upon successful install of the library and managed to run it via PHP script, it's throwing this error below.

Warning: file_get_contents(/tmp/gears-pdf-libreoffice/generated/GearsPdfvtISnh.pdf): failed to open stream

Have anyone had the same issue and figured it out? Thanks

**Comment by bjoern-vh** [comment]
Same here...

Current version 0.4.1 installed with composer.

**Comment by MarZab** [comment]
I had this error before installing openoffice-base and libreoffice-common on debian.

**Comment by bjoern-vh** [comment]
That's it. I already installed libreoffice-common but not openoffice-base. In my case on Ubuntu 16.04 libreoffice-base. Now it's working for me. Thanks a lot :-)

**Comment by mjaseo** [comment]
Hello and thank you for your replies. Whilst your suggestion worked, I wasn't able to install openoffice-base on Debian 8 (x86_64) as it said package not found and instead installed "libreoffice-base" and it fixed the issue as well.

Again, thank you guys for helping me out. Cheers :)
